# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3084f7fdeead18d25600fbdb695ece6a5cecf204cffa3d1bdabf89f156b72debf40f83d5bc7bdfe82122a5474c8f618e1a83aeba4b452a7c6a5728b35a228745

test:
  secret_key_base: 5c382b681c47acc57213052a82f330eef53d07a3f886454f43758c3bb10256a130d7deb0970b589c3e76e3089dec52b1b75fa9f5d59a61e55c20e23a7bf2718c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
